import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import AppNav from "@/components/app-nav";

const euclid = localFont({
  src: [
    {
      path: "../public/fonts/Euclid-Circular-B-Bold.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Euclid-Circular-B-Light.ttf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-euclid",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${euclid.variable} ${geistMono.variable} ${geistSans.variable} antialiased`}
      >
        <AppNav />
        <main className="costume-padding bg-[#FBFCFC]">
          <div className=" py-2">
            <h1 className="user text-xl font-bold">Welcome, Ahmed</h1>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
